name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d rails_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/rails_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: true

      - name: Set up Node & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install JS deps
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          fi

      - name: Prepare database
        run: |
          bin/rails db:create db:schema:load
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Run tests
        run: |
          bin/rails test
